# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

# Select image from https://hub.docker.com/_/php/
image: php:8.2

# Select what we should cache
cache:
  paths:
    - vendor/

before_script:
  # Install git and zip library, the php image doesn't have installed
  - apt update -yqq
  - apt install git libzip-dev zip -yqq

  # Install PHP extensions: xdebug
  - pecl install xdebug
  - docker-php-ext-install xdebug zip

  # Install composer
  - curl -sS https://getcomposer.org/installer | php

  # Install all project dependencies
  - php composer.phar install

test:php8.2:
  script:
    - composer run test

test:php8.1:
  image: php:8.1
  script:
    - composer run test

test:php8.0:
  image: php:8.0
  script:
    - composer run test
